#pragma once

#include "BUILD_OPTIONS.h"
#include "Platform.h"

#if USE_FRAMEWORK_GLFW

enum KeyboardKeycode
{
	KEY_LEFT = GLFW_KEY_LEFT,
	KEY_RIGHT = GLFW_KEY_RIGHT,
	KEY_UP = GLFW_KEY_UP,
	KEY_DOWN = GLFW_KEY_DOWN,
	KEY_NUM_0 = GLFW_KEY_0,
	KEY_NUM_1 = GLFW_KEY_1,
	KEY_NUM_2 = GLFW_KEY_2,
	KEY_NUM_3 = GLFW_KEY_3,
	KEY_NUM_4 = GLFW_KEY_4,
	KEY_NUM_5 = GLFW_KEY_5,
	KEY_NUM_6 = GLFW_KEY_6,
	KEY_NUM_7 = GLFW_KEY_7,
	KEY_NUM_8 = GLFW_KEY_8,
	KEY_NUM_9 = GLFW_KEY_9
};

#endif